version: "2"
services:
  postgresql:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: "miniware"
      POSTGRES_PASSWORD: "developer"
    ports:
      - "8888:5432"
    networks:
      - "main"
networks:
  main:
    driver: "bridge"

